### PR TITLE
ItemNav Bug Fix

### LINKED ISSUE #664: ItemNav open button misaligned
The border on the left side of the button to open the itemnav is cut off on the [nightly.opencircuits.io](nightly.opencircuits.io) site, but is not on [opencircuits.io](opencircuits.io)

On [opencircuits.io](opencircuits.io):
image

On [nightly.opencircuits.io](nightly.opencircuits.io)
image

### LINKED ISSUE #682: ItemNav Tab is too far right
**Describe the bug**
The ItemNav tab to open/close the ItemNav is off of the left-side of the screen

**Screenshots**
Screen Shot 2021-07-23 at 11 12 24 AM

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 91.0.4472.164

### PR DESCRIPTION
**Pull request by SamooMei**
Description: Button is now properly aligned and now transitions smoothly

Issue #664 
| Before     | After |
| ---      | ---       |
|BeforeFix | Fix |

Fixes #664 
Edit: Fixes #682 as well
Edit 2: It doesn't teleport now :joy_cat: 
Edit 3: Scrollbars & Static Top :scream:

### CODE REVIEW

**Comment by LeonMontealegre** [comment]
It isn't working for me? Maybe has to do with the newest code-changes but can you test it again?

It works when opening the ItemNav, but it teleports when closing it.

I assume because you removed `transition: 0.5s` ?

**Comment by LeonMontealegre** [comment]
@KevinMackenzie @TGCrystal  can you guys test it too to confirm?

**Comment by KevinMackenzie** [comment]
Can confirm, it does teleport when closing.

**Comment by TGCrystal** [comment]
Happens to me even with the `transition: 0.5s;` line added back in.

**Review by LeonMontealegre — CHANGES_REQUESTED** [review]
Currently it teleports when closing the ItemNav

**Comment by SamooMei** [comment]
Apparently the teleportation was because both commits conflicted with each other so I changed it up and now it _should_ work properly

**Pull request merged**
